/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package mojo.parse;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 57;
  /** RegularExpression Id. */
  int NUMBER = 58;
  /** RegularExpression Id. */
  int CHAR = 59;
  /** RegularExpression Id. */
  int TEXT = 60;
  /** RegularExpression Id. */
  int ESCAPE = 61;
  /** RegularExpression Id. */
  int OctalDigit = 62;
  /** RegularExpression Id. */
  int PRINTINGCHAR = 63;
  /** RegularExpression Id. */
  int HexDigit = 64;
  /** RegularExpression Id. */
  int DIGIT = 65;
  /** RegularExpression Id. */
  int LETTER = 66;
  /** RegularExpression Id. */
  int OTHERCHAR = 67;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\"break\"",
    "\"class\"",
    "\"const\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"loop\"",
    "\"method\"",
    "\"override\"",
    "\"proc\"",
    "\"return\"",
    "\"struct\"",
    "\"type\"",
    "\"until\"",
    "\"val\"",
    "\"var\"",
    "\"while\"",
    "\"||\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"&&\"",
    "\">\"",
    "\">=\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\".\"",
    "\"==\"",
    "\"!\"",
    "\"!=\"",
    "\"..\"",
    "\"%\"",
    "\"[\"",
    "\"]\"",
    "\":=\"",
    "\"=\"",
    "\"^\"",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 56>",
    "<ID>",
    "<NUMBER>",
    "<CHAR>",
    "<TEXT>",
    "<ESCAPE>",
    "<OctalDigit>",
    "<PRINTINGCHAR>",
    "<HexDigit>",
    "<DIGIT>",
    "<LETTER>",
    "<OTHERCHAR>",
  };

}
